apiVersion: v1
kind: Pod
metadata:
  name: tomcatpod1affi
    spec:
      affinity:
        nodeAffinity:
          RequiredDuringSchedulingIgnoredDuringExecution:
            preference:
              matchExpressions:
              - key: size
                operator: In
                values:
                  - small      
    containers:
      - name: tomcat
        image: ravindra45/ravindra45:1.1.1

