apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: tomcat-nginix
      labels:
        app: tomcat
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
               matchExpressions:
               - key: app
                 operator: In
                 values:
                 - tomcat
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: tomcat
          image: ravindra45/ravindra45:1.1.1

